using System;
using System.Collections.Generic;

namespace LoLCompanion
{
    public static class GameData
    {
        public static Dictionary<long, string> ItemNames = new Dictionary<long, string>
        {
            { 1001, "Boots of Speed" },
            { 1004, "Faerie Charm" },
            { 1006, "Kindlegem" },
            { 1011, "Giant's Belt" },
            { 1018, "Cloak of Agility" },
            { 1026, "Spectre's Cowl" },
            { 1031, "Chainmail" },
            { 1033, "Kindlegem" },
            { 1037, "Spectre's Cowl" },
            { 1038, "Spectre's Cowl" },
            { 1039, "Kindlegem" },
            { 1040, "Giant's Belt" },
            { 1041, "Giant's Belt" },
            { 1042, "Chainmail" },
            { 1043, "Kindlegem" },
            { 1044, "Giant's Belt" },
            { 1045, "Cloak of Agility" },
            { 1046, "Spectre's Cowl" },
            { 1047, "Cloak of Agility" },
            { 1048, "Negatron Cloak" },
            { 1052, "Kindlegem" },
            { 1057, "Spectre's Cowl" },
            { 2003, "Spectre's Cowl" },
            { 2010, "Control Ward" },
            { 2031, "Kaenic Rookern" },
            { 2033, "Kaenic Rookern" },
            { 2065, "Spirit Visage" },
            { 2138, "Spectre's Cowl" },
            { 2139, "Negatron Cloak" },
            { 2140, "Adaptive Force" },
            { 2141, "Negatron Cloak" },
            { 2142, "Spectre's Cowl" },
            { 2143, "Null-Magic Mantle" },
            { 2144, "Negatron Cloak" },
            { 2150, "Null-Magic Mantle" },
            { 2152, "Negatron Cloak" },
            { 2155, "Null-Magic Mantle" },
            { 3001, "Rod of Ages" },
            { 3003, "Archangel's Staff" },
            { 3006, "Abyssal Mask" },
            { 3009, "Adaptive Force" },
            { 3011, "Spectre's Cowl" },
            { 3020, "Mana" },
            { 3024, "Morellonomicon" },
            { 3025, "Spirit Visage" },
            { 3026, "Zhonya's Hourglass" },
            { 3027, "Rod of Ages" },
            { 3031, "Sunfire Aegis" },
            { 3033, "Morellonomicon" },
            { 3034, "Adaptive Force" },
            { 3035, "Adaptive Force" },
            { 3036, "Negatron Cloak" },
            { 3040, "Bandleglass Mirrordancer" },
            { 3041, "Kaenic Rookern" },
            { 3043, "Adaptive Force" },
            { 3044, "Adaptive Force" },
            { 3045, "Kaenic Rookern" },
            { 3046, "Hollow Radiance" },
            { 3050, "Rylai's Crystal Scepter" },
            { 3051, "Rylai's Crystal Scepter" },
            { 3057, "Rylai's Crystal Scepter" },
            { 3065, "Spirit Visage" },
            { 3066, "Adaptive Force" },
            { 3067, "Adaptive Force" },
            { 3068, "Adaptive Force" },
            { 3069, "Adaptive Force" },
            { 3070, "Adaptive Force" },
            { 3071, "Adaptive Force" },
            { 3072, "Adaptive Force" },
            { 3073, "Adaptive Force" },
            { 3074, "Adaptive Force" },
            { 3075, "Adaptive Force" },
            { 3076, "Spectre's Cowl" },
            { 3077, "Adaptive Force" },
            { 3078, "Spectre's Cowl" },
            { 3082, "Rod of Ages" },
            { 3083, "Abyssal Mask" },
            { 3084, "Adaptive Force" },
            { 3085, "Adaptive Force" },
            { 3086, "Adaptive Force" },
            { 3087, "Adaptive Force" },
            { 3089, "Zhonia's Hourglass" },
            { 3091, "Bandleglass Mirrordancer" },
            { 3092, "Adaptive Force" },
            { 3093, "Adaptive Force" },
            { 3094, "Adaptive Force" },
            { 3095, "Adaptive Force" },
            { 3096, "Adaptive Force" },
            { 3097, "Adaptive Force" },
            { 3098, "Adaptive Force" },
            { 3099, "Adaptive Force" },
            { 3100, "Adaptive Force" },
            { 3101, "Adaptive Force" },
            { 3102, "Adaptive Force" },
            { 3103, "Adaptive Force" },
            { 3104, "Adaptive Force" },
            { 3105, "Adaptive Force" },
            { 3106, "Adaptive Force" },
            { 3107, "Adaptive Force" },
            { 3108, "Adaptive Force" },
            { 3109, "Adaptive Force" },
            { 3110, "Adaptive Force" },
            { 3111, "Adaptive Force" },
            { 3112, "Adaptive Force" },
            { 3113, "Adaptive Force" },
            { 3114, "Adaptive Force" },
            { 3115, "Adaptive Force" },
            { 3116, "Adaptive Force" },
            { 3117, "Adaptive Force" },
            { 3118, "Adaptive Force" },
            { 3119, "Adaptive Force" },
            { 3120, "Adaptive Force" },
            { 3121, "Adaptive Force" },
            { 3122, "Adaptive Force" },
            { 3123, "Adaptive Force" },
            { 3124, "Adaptive Force" },
            { 3125, "Adaptive Force" },
            { 3126, "Adaptive Force" },
            { 3127, "Adaptive Force" },
            { 3128, "Adaptive Force" },
            { 3129, "Adaptive Force" },
            { 3130, "Adaptive Force" },
            { 3131, "Adaptive Force" },
            { 3132, "Adaptive Force" },
            { 3133, "Adaptive Force" },
            { 3134, "Adaptive Force" },
            { 3135, "Adaptive Force" },
            { 3136, "Adaptive Force" },
            { 3137, "Adaptive Force" },
            { 3138, "Adaptive Force" },
            { 3139, "Adaptive Force" },
            { 3140, "Adaptive Force" },
            { 3141, "Adaptive Force" },
            { 3142, "Adaptive Force" },
            { 3143, "Adaptive Force" },
            { 3144, "Adaptive Force" },
            { 3145, "Adaptive Force" },
            { 3146, "Adaptive Force" },
            { 3147, "Adaptive Force" },
            { 3148, "Adaptive Force" },
            { 3149, "Adaptive Force" },
            { 3150, "Adaptive Force" },
            { 3151, "Adaptive Force" },
            { 3152, "Adaptive Force" },
            { 3153, "Adaptive Force" },
            { 3154, "Adaptive Force" },
            { 3155, "Adaptive Force" },
            { 3156, "Adaptive Force" },
            { 3157, "Adaptive Force" }
        };

        public static Dictionary<long, string> RuneNames = new Dictionary<long, string>
        {
            { 8005, "Precision" },
            { 8008, "Press the Attack" },
            { 8009, "Lethal Tempo" },
            { 8010, "Conqueror" },
            { 8014, "Triumph" },
            { 8017, "Legend: Alacrity" },
            { 8021, "Cut Down" },
            { 8112, "Sorcery" },
            { 8124, "Summon Aery" },
            { 8128, "Manaflow Band" },
            { 8138, "Celerity" },
            { 8139, "Absolute Focus" },
            { 8143, "Gathering Storm" },
            { 8214, "Resolve" },
            { 8242, "Glacial Augment" },
            { 8243, "Unsealed Spellbook" },
            { 8299, "First Strike" },
            { 8304, "Inspiration" },
            { 8306, "Hextech Flashtraption" },
            { 8313, "Biscuit Delivery" },
            { 8316, "Cosmic Insight" },
            { 8410, "Domination" },
            { 8437, "Cheap Shot" },
            { 8439, "Sudden Impact" },
            { 8465, "Eyeball Collection" },
            { 8472, "Relentless Hunter" },
            { 9101, "Adaptive Force +9" },
            { 9103, "Armor +6" },
            { 9105, "Magic Resist +8" },
            { 9111, "Adaptive Force +9" },
            { 9104, "Armor +6" },
            { 9224, "Cosmic Insight" },
            { 9226, "Approach Velocity" }
        };

        public static Dictionary<long, string> RuneIconPaths = new Dictionary<long, string>
        {
            { 8005, "/lol-perks/v1/styles/precision.png" },
            { 8008, "/lol-perks/v1/keystones/presstheattack.png" },
            { 8009, "/lol-perks/v1/keystones/letaltempocon.png" },
            { 8010, "/lol-perks/v1/keystones/conquerorcon.png" },
            { 8014, "/lol-perks/v1/keystones/triumph.png" },
            { 8017, "/lol-perks/v1/keystones/legendalacrity.png" },
            { 8021, "/lol-perks/v1/keystones/cutdown.png" },
            { 8112, "/lol-perks/v1/styles/sorcery.png" },
            { 8124, "/lol-perks/v1/keystones/summonaery.png" },
            { 8128, "/lol-perks/v1/keystones/manaflowband.png" },
            { 8138, "/lol-perks/v1/keystones/celerity.png" },
            { 8139, "/lol-perks/v1/keystones/absolutefocus.png" },
            { 8143, "/lol-perks/v1/keystones/gatheringstorm.png" },
            { 8214, "/lol-perks/v1/styles/resolve.png" },
            { 8242, "/lol-perks/v1/keystones/glacialaugment.png" },
            { 8243, "/lol-perks/v1/keystones/unsealedspellbook.png" },
            { 8299, "/lol-perks/v1/keystones/firststrike.png" },
            { 8304, "/lol-perks/v1/styles/inspiration.png" },
            { 8306, "/lol-perks/v1/keystones/hextech.png" },
            { 8313, "/lol-perks/v1/keystones/biscuitdelivery.png" },
            { 8316, "/lol-perks/v1/keystones/cosmicinsight.png" },
            { 8410, "/lol-perks/v1/styles/domination.png" },
            { 8437, "/lol-perks/v1/keystones/cheapshot.png" },
            { 8439, "/lol-perks/v1/keystones/suddenimpact.png" },
            { 8465, "/lol-perks/v1/keystones/eyeballcollection.png" },
            { 8472, "/lol-perks/v1/keystones/relentlesshunter.png" },
            { 9101, "/lol-perks/v1/shards/adaptiveforce.png" },
            { 9103, "/lol-perks/v1/shards/armor.png" },
            { 9105, "/lol-perks/v1/shards/magicresist.png" },
            { 9111, "/lol-perks/v1/shards/adaptiveforce.png" },
            { 9104, "/lol-perks/v1/shards/armor.png" },
            { 9224, "/lol-perks/v1/shards/cosmicinsight.png" },
            { 9226, "/lol-perks/v1/shards/approachvelocity.png" }
        };
    }
}
